name: lab4
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - alabaster=1.0.0
  - altair=5.5.0
  - annotated-types=0.7.0
  - anyio=4.10.0
  - appnope=0.1.4
  - archspec=0.2.5
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - asttokens=3.0.0
  - astunparse=1.6.3
  - async-lru=2.0.5
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.5
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blinker=1.9.0
  - boltons=25.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.11.12
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - catalogue=2.0.10
  - certifi=2025.11.12
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - click=8.2.1
  - cloudpathlib=0.23.0
  - cloudpickle=3.1.2
  - colorama=0.4.6
  - comm=0.2.3
  - conda=25.7.0
  - conda-libmamba-solver=25.3.0
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - confection=0.1.5
  - contourpy=1.3.3
  - cpp-expected=1.1.0
  - cpython=3.12.11
  - cryptography=45.0.6
  - cycler=0.12.1
  - cymem=2.0.13
  - cython-blis=1.3.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - distro=1.9.0
  - docutils=0.21.2
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fica=0.4.1
  - fmt=11.1.4
  - fqdn=1.5.1
  - freetype=2.14.1
  - frozendict=2.4.6
  - frozenlist=1.7.0
  - gitdb=4.0.12
  - gitpython=3.1.45
  - google-api-core=2.25.1
  - google-api-python-client=2.179.0
  - google-auth=2.40.3
  - google-auth-httplib2=0.2.0
  - google-auth-oauthlib=1.2.2
  - googleapis-common-protos=1.70.0
  - h11=0.16.0
  - h2=4.2.0
  - hpack=4.1.0
  - httpcore=1.0.9
  - httplib2=0.22.0
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagesize=1.4.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipylab=1.1.0
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jieba=0.42.1
  - jinja2=3.1.6
  - joblib=1.5.2
  - json5=0.12.1
  - jsonpatch=1.33
  - jsonpointer=3.0.0
  - jsonschema=4.25.1
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.1
  - jupyter-lsp=2.2.6
  - jupyter-server-mathjax=0.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.17.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab-git=0.51.2
  - jupyterlab-spellchecker=0.8.4
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jupytext=1.17.2
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lark=1.2.2
  - lcms2=2.17
  - lerc=4.0.0
  - libabseil=20250512.1
  - libarchive=3.7.7
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=20.1.8
  - libdeflate=1.25
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.2
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmamba=2.1.1
  - libmambapy=2.1.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - libsodium=1.0.20
  - libsolv=0.7.34
  - libsqlite=3.50.3
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.13.8
  - libxslt=1.1.43
  - libzlib=1.3.1
  - llvm-openmp=20.1.8
  - lxml=6.0.2
  - lz4-c=1.10.0
  - lzo=2.10
  - mamba=2.1.1
  - markdown-it-py=4.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.8
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.2
  - menuinst=2.3.1
  - mistune=3.1.3
  - multidict=6.6.3
  - munkres=1.1.4
  - murmurhash=1.0.15
  - narwhals=2.2.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbdime=4.0.2
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nlohmann_json=3.11.3
  - nltk=3.9.2
  - notebook-shim=0.2.4
  - numpy=2.3.2
  - oauthlib=3.3.1
  - openjpeg=2.5.4
  - openssl=3.6.0
  - otter-grader=6.1.4
  - overrides=7.7.0
  - packaging=25.0
  - palmerpenguins=0.1.4
  - pandas=2.3.2
  - pandocfilters=1.5.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=12.0.0
  - pip=25.1.1
  - platformdirs=4.3.8
  - pluggy=1.6.0
  - preshed=3.0.12
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - proto-plus=1.26.1
  - protobuf=6.31.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyasn1=0.6.1
  - pyasn1-modules=0.4.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pyobjc-core=11.1
  - pyobjc-framework-cocoa=11.1
  - pyopenssl=25.1.0
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.2
  - python-gil=3.12.11
  - python-json-logger=2.0.7
  - python-on-whales=0.78.0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - pyu2f=0.1.5
  - pyyaml=6.0.2
  - pyzmq=27.0.2
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - regex=2025.11.3
  - reproc=14.2.5.post0
  - reproc-cpp=14.2.5.post0
  - requests=2.32.4
  - requests-oauthlib=2.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - roman-numerals-py=3.1.0
  - rpds-py=0.27.0
  - rsa=4.9.1
  - ruamel.yaml=0.18.14
  - ruamel.yaml.clib=0.2.8
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shellingham=1.5.4
  - simdjson=3.12.3
  - six=1.17.0
  - smart-open=7.5.0
  - smart_open=7.5.0
  - smmap=5.0.2
  - sniffio=1.3.1
  - snowballstemmer=3.0.1
  - soupsieve=2.7
  - spacy=3.8.11
  - spacy-legacy=3.0.12
  - spacy-loggers=1.0.5
  - sphinx=8.2.3
  - sphinxcontrib-applehelp=2.0.0
  - sphinxcontrib-devhelp=2.0.0
  - sphinxcontrib-htmlhelp=2.1.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=2.0.0
  - sphinxcontrib-serializinghtml=1.1.10
  - srsly=2.5.2
  - stack_data=0.6.3
  - terminado=0.18.1
  - thinc=8.3.10
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - tomli=2.2.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - typer=0.16.1
  - typer-slim=0.16.1
  - typer-slim-standard=0.16.1
  - types-python-dateutil=2.9.0.20250822
  - typing-extensions=4.15.0
  - typing-inspection=0.4.1
  - typing_extensions=4.15.0
  - typing_utils=0.1.0
  - tzdata=2025b
  - ujson=5.11.0
  - unicodedata2=17.0.0
  - uri-template=1.3.0
  - uritemplate=4.2.0
  - urllib3=2.5.0
  - wasabi=1.1.3
  - wcwidth=0.2.13
  - weasel=0.4.3
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wordcloud=1.9.4
  - wrapt=1.17.3
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib-ng=2.2.5
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - altair-ally==0.1.1
      - arro3-core==0.6.5
      - audeer==2.3.1
      - audformat==1.3.2
      - audinterface==1.3.1
      - audiofile==1.5.1
      - audmath==1.4.4
      - audobject==0.7.12
      - audresample==1.3.5
      - et-xmlfile==2.0.0
      - fonttools==4.59.2
      - greenlet==3.2.4
      - iniconfig==2.1.0
      - iso3166==2.1.1
      - iso639-lang==2.6.3
      - matplotlib==3.10.6
      - nycflights13==0.0.3
      - openpyxl==3.1.5
      - opensmile==2.6.0
      - oyaml==1.0
      - playwright==1.54.0
      - pyarrow==22.0.0
      - pyee==13.0.0
      - pytest==8.4.2
      - seaborn==0.13.2
      - soundfile==0.13.1
      - vega-datasets==0.9.0
      - vegafusion==2.0.3
      - vl-convert-python==1.8.0
